# NN2 (wine classification)


In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn import datasets

In [2]:
wine = datasets.load_wine()

In [3]:
inputs = wine.data
inputs

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [4]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [5]:
outputs = wine.target
outputs

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [6]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [7]:
inputs.shape

(178, 13)

In [8]:
outputs.shape

(178,)

## Train and test datasets

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, outputs, test_size = 0.2)

In [10]:
X_train.shape

(142, 13)

In [11]:
y_train.shape

(142,)

In [12]:
X_test.shape

(36, 13)

In [13]:
y_test.shape

(36,)

## Neural network (training)

In [14]:
(13 + 3) / 2

8.0

In [15]:
# 13 -> 8 -> 8 -> 3
network = MLPClassifier(max_iter=2000,
                        verbose=True,
                        activation = 'logistic',
                        solver = 'adam',
                        learning_rate = 'constant',
                        learning_rate_init = 0.001,
                        tol=0.00000100,
                        hidden_layer_sizes = (8, 8))
network.fit(X_train, y_train)

Iteration 1, loss = 1.14786119
Iteration 2, loss = 1.14602425
Iteration 3, loss = 1.14424278
Iteration 4, loss = 1.14251358
Iteration 5, loss = 1.14083404
Iteration 6, loss = 1.13920211
Iteration 7, loss = 1.13761614
Iteration 8, loss = 1.13607471
Iteration 9, loss = 1.13457652
Iteration 10, loss = 1.13312025
Iteration 11, loss = 1.13170449
Iteration 12, loss = 1.13032764
Iteration 13, loss = 1.12898791
Iteration 14, loss = 1.12768331
Iteration 15, loss = 1.12641174
Iteration 16, loss = 1.12517100
Iteration 17, loss = 1.12395888
Iteration 18, loss = 1.12277317
Iteration 19, loss = 1.12161162
Iteration 20, loss = 1.12047188
Iteration 21, loss = 1.11935122
Iteration 22, loss = 1.11824627
Iteration 23, loss = 1.11715252
Iteration 24, loss = 1.11606383
Iteration 25, loss = 1.11497171
Iteration 26, loss = 1.11386450
Iteration 27, loss = 1.11272635
Iteration 28, loss = 1.11153663
Iteration 29, loss = 1.11027079
Iteration 30, loss = 1.10890276
Iteration 31, loss = 1.10740594
Iteration 32, los

Iteration 407, loss = 0.72432392
Iteration 408, loss = 0.72308712
Iteration 409, loss = 0.72185718
Iteration 410, loss = 0.72063441
Iteration 411, loss = 0.71941696
Iteration 412, loss = 0.71820497
Iteration 413, loss = 0.71700010
Iteration 414, loss = 0.71580296
Iteration 415, loss = 0.71461265
Iteration 416, loss = 0.71342881
Iteration 417, loss = 0.71225242
Iteration 418, loss = 0.71108426
Iteration 419, loss = 0.70992410
Iteration 420, loss = 0.70877151
Iteration 421, loss = 0.70762655
Iteration 422, loss = 0.70648977
Iteration 423, loss = 0.70536145
Iteration 424, loss = 0.70424143
Iteration 425, loss = 0.70312943
Iteration 426, loss = 0.70202530
Iteration 427, loss = 0.70092918
Iteration 428, loss = 0.69984115
Iteration 429, loss = 0.69876116
Iteration 430, loss = 0.69768905
Iteration 431, loss = 0.69662458
Iteration 432, loss = 0.69556757
Iteration 433, loss = 0.69451790
Iteration 434, loss = 0.69347548
Iteration 435, loss = 0.69244022
Iteration 436, loss = 0.69141201
Iteration 

Iteration 805, loss = 0.48747738
Iteration 806, loss = 0.48684857
Iteration 807, loss = 0.48621864
Iteration 808, loss = 0.48558931
Iteration 809, loss = 0.48496136
Iteration 810, loss = 0.48433905
Iteration 811, loss = 0.48372038
Iteration 812, loss = 0.48311173
Iteration 813, loss = 0.48249214
Iteration 814, loss = 0.48186291
Iteration 815, loss = 0.48117899
Iteration 816, loss = 0.48046417
Iteration 817, loss = 0.47973218
Iteration 818, loss = 0.47903148
Iteration 819, loss = 0.47837410
Iteration 820, loss = 0.47773924
Iteration 821, loss = 0.47709509
Iteration 822, loss = 0.47641271
Iteration 823, loss = 0.47570291
Iteration 824, loss = 0.47498657
Iteration 825, loss = 0.47429014
Iteration 826, loss = 0.47361537
Iteration 827, loss = 0.47294446
Iteration 828, loss = 0.47225953
Iteration 829, loss = 0.47155191
Iteration 830, loss = 0.47083377
Iteration 831, loss = 0.47011894
Iteration 832, loss = 0.46941519
Iteration 833, loss = 0.46871784
Iteration 834, loss = 0.46801612
Iteration 

Iteration 1219, loss = 0.15330497
Iteration 1220, loss = 0.15330414
Iteration 1221, loss = 0.15250916
Iteration 1222, loss = 0.15149500
Iteration 1223, loss = 0.15166494
Iteration 1224, loss = 0.15143058
Iteration 1225, loss = 0.15012792
Iteration 1226, loss = 0.15026114
Iteration 1227, loss = 0.15010166
Iteration 1228, loss = 0.14878185
Iteration 1229, loss = 0.14909694
Iteration 1230, loss = 0.14873349
Iteration 1231, loss = 0.14747147
Iteration 1232, loss = 0.14801000
Iteration 1233, loss = 0.14728176
Iteration 1234, loss = 0.14630302
Iteration 1235, loss = 0.14679191
Iteration 1236, loss = 0.14560105
Iteration 1237, loss = 0.14522782
Iteration 1238, loss = 0.14514214
Iteration 1239, loss = 0.14403936
Iteration 1240, loss = 0.14404857
Iteration 1241, loss = 0.14335785
Iteration 1242, loss = 0.14289860
Iteration 1243, loss = 0.14269844
Iteration 1244, loss = 0.14196142
Iteration 1245, loss = 0.14185612
Iteration 1246, loss = 0.14125664
Iteration 1247, loss = 0.14085158
Iteration 1248

Iteration 1601, loss = 0.06555059
Iteration 1602, loss = 0.06544519
Iteration 1603, loss = 0.06534009
Iteration 1604, loss = 0.06523527
Iteration 1605, loss = 0.06513075
Iteration 1606, loss = 0.06502652
Iteration 1607, loss = 0.06492257
Iteration 1608, loss = 0.06481891
Iteration 1609, loss = 0.06471553
Iteration 1610, loss = 0.06461244
Iteration 1611, loss = 0.06450962
Iteration 1612, loss = 0.06440709
Iteration 1613, loss = 0.06430484
Iteration 1614, loss = 0.06420287
Iteration 1615, loss = 0.06410117
Iteration 1616, loss = 0.06399975
Iteration 1617, loss = 0.06389860
Iteration 1618, loss = 0.06379772
Iteration 1619, loss = 0.06369712
Iteration 1620, loss = 0.06359679
Iteration 1621, loss = 0.06349672
Iteration 1622, loss = 0.06339693
Iteration 1623, loss = 0.06329740
Iteration 1624, loss = 0.06319814
Iteration 1625, loss = 0.06309914
Iteration 1626, loss = 0.06300041
Iteration 1627, loss = 0.06290193
Iteration 1628, loss = 0.06280372
Iteration 1629, loss = 0.06270577
Iteration 1630

Iteration 1991, loss = 0.03927597
Iteration 1992, loss = 0.03923096
Iteration 1993, loss = 0.03918601
Iteration 1994, loss = 0.03914113
Iteration 1995, loss = 0.03909631
Iteration 1996, loss = 0.03905156
Iteration 1997, loss = 0.03900687
Iteration 1998, loss = 0.03896224
Iteration 1999, loss = 0.03891767
Iteration 2000, loss = 0.03887317


C:\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(activation='logistic', hidden_layer_sizes=(8, 8), max_iter=2000,
              tol=1e-06, verbose=True)

In [16]:
network.classes_

array([0, 1, 2])

In [17]:
network.coefs_

[array([[ 8.26202545e-01, -9.98347316e-03, -5.98005690e-01,
         -9.56205289e-02,  5.08713945e-01,  3.56892390e-02,
         -1.19315098e-01,  7.69440178e-01],
        [-9.41054169e-01,  1.15285354e+00,  7.02797756e-01,
         -1.09487928e-01, -9.19960185e-02,  1.06114910e+00,
          4.67734879e-01, -1.01309107e+00],
        [-1.76780805e+00,  1.42864669e+00,  1.31629191e+00,
         -9.92000835e-02, -9.11354031e-01,  6.77554551e-01,
          8.30801187e-02, -1.32790556e+00],
        [ 9.24569073e-02, -8.38312381e-01, -4.33212351e-01,
          8.95238238e-02,  2.87113878e-01, -9.86410272e-01,
          7.81094220e-03,  2.40954097e-01],
        [-1.32878419e-02, -1.48043758e-02,  3.67541141e-02,
          1.62967210e-01, -4.33197619e-02, -1.16632454e-01,
          2.41734805e-02, -4.28451963e-02],
        [ 4.57760592e-01, -1.98163509e-06, -1.11812435e-01,
          4.33971459e-02, -7.43568073e-01, -8.79740258e-02,
         -2.65362450e-01, -7.69047563e-01],
        [-4.8560

In [18]:
network.intercepts_

[array([ 1.69797648, -1.43037038, -1.98512144,  0.07614826,  0.89221706,
        -0.66330959, -0.31453464,  2.06311709]),
 array([ 0.24291929,  0.00357639,  0.57397273,  0.25403998,  0.16104029,
         0.29628113, -0.20232746, -0.46541479]),
 array([-0.78129943,  1.93498603,  0.06325396])]

In [19]:
network.n_layers_

4

In [20]:
network.n_outputs_

3

In [21]:
network.out_activation_

'softmax'

## Neural network (evaluation)

In [22]:
X_test.shape

(36, 13)

In [23]:
predictions = network.predict(X_test)
predictions

array([2, 1, 0, 0, 0, 1, 1, 2, 2, 1, 2, 0, 0, 2, 1, 2, 1, 2, 2, 1, 2, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 2, 1, 1])

In [24]:
y_test

array([2, 1, 0, 0, 0, 1, 1, 2, 2, 1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 1, 2, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 2, 1, 1])

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, predictions)

0.9722222222222222

In [26]:
cm = confusion_matrix(y_test, predictions)
cm

array([[11,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

## Neural network (classification)

In [29]:
X_test[0], y_test[0]

(array([1.352e+01, 3.170e+00, 2.720e+00, 2.350e+01, 9.700e+01, 1.550e+00,
        5.200e-01, 5.000e-01, 5.500e-01, 4.350e+00, 8.900e-01, 2.060e+00,
        5.200e+02]),
 2)

In [30]:
X_test[0].shape

(13,)

In [31]:
new = X_test[0].reshape(1, -1)
new.shape

(1, 13)

In [32]:
new

array([[1.352e+01, 3.170e+00, 2.720e+00, 2.350e+01, 9.700e+01, 1.550e+00,
        5.200e-01, 5.000e-01, 5.500e-01, 4.350e+00, 8.900e-01, 2.060e+00,
        5.200e+02]])

In [33]:
network.predict(new)

array([2])

In [34]:
wine.target_names[network.predict(new)]

array(['class_2'], dtype='<U7')